import Foundation

/// A tool call in flight, per PreToolUse/PostToolUse hook events.
struct ToolActivity: Equatable, Sendable {
    let toolName: String
    let summary: String?     // "npm test", "Sources/App.swift", a URL…
    let startedAt: Date
}

/// A `PermissionRequest` whose HTTP response is being held open so the user
/// can Allow/Deny from Compagnion. Resolved via
/// `SessionMonitor.resolveApproval`; times out to the terminal prompt.
struct PendingApproval: Identifiable, Equatable, Sendable {
    let id: UUID
    let sessionId: String
    let toolName: String?
    let summary: String?
    let receivedAt: Date
}

/// What the panel draws for one session: the authoritative row from
/// `claude agents --json` plus whatever enrichment happened to be available.
/// Every enriched field is optional on purpose — the UI must render correctly
/// from the poll alone, and must never fabricate a number it doesn't have.
struct SessionDisplay: Identifiable, Equatable {
    let session: ClaudeSession

    /// Phase 3 — from `~/.claude/projects/<slug>/sessions-index.json`.
    var gitBranch: String?
    var firstPrompt: String?
    var messageCount: Int?

    /// Claude Code's own rolling summary of what this session is about.
    var aiTitle: String?

    /// Phase 5 — statusline-reported, or computed from the transcript tail.
    var contextFraction: Double?
    var contextMeasuredAt: Date?

    /// Phase 5 — live count from SubagentStart/SubagentStop hook events.
    var subagentCount: Int = 0

    /// A hook told us this session is blocked on the user. Hooks land within
    /// milliseconds; the poll that confirms it may be seconds away, so the
    /// event wins until the next poll agrees or clears it.
    var waitingOverride = false

    /// Tool named by the hook that blocked this session, e.g. "Bash". The poll
    /// only reports a coarse `waitingFor`, so this is the better label when
    /// the event got here first.
    var pendingToolName: String?

    /// What the session is doing right now (PreToolUse → PostToolUse window).
    var activity: ToolActivity?

    /// The question a session is asking (Elicitation / AskUserQuestion),
    /// verbatim, while it waits for an answer in the terminal.
    var question: String?

    /// The last turn ended with an API error (StopFailure) and nothing has
    /// happened since.
    var hadError = false

    /// A permission request currently held open for remote Allow/Deny.
    var pendingApproval: PendingApproval?

    var id: String { session.id }

    init(session: ClaudeSession) {
        self.session = session
    }

    /// What the card is titled. A name the user chose with `claude --name`
    /// always wins; otherwise Claude Code's `ai-title` beats the
    /// auto-generated `<folder>-<hex>` label, which says nothing.
    var title: String {
        if let name = session.name, !name.isEmpty, !Self.isAutoGenerated(name, cwd: session.cwd) {
            return name
        }
        if let aiTitle, !aiTitle.isEmpty { return aiTitle }
        return session.displayName
    }

    /// Claude Code names unnamed sessions `<folder>-<two hex chars>`.
    static func isAutoGenerated(_ name: String, cwd: String) -> Bool {
        let folder = (cwd as NSString).lastPathComponent
        guard name.count > folder.count + 1, name.hasPrefix(folder + "-") else { return false }
        let suffix = name.dropFirst(folder.count + 1)
        return suffix.allSatisfy(\.isHexDigit)
    }

    var badge: SessionBadge {
        if session.needsAttention || waitingOverride { return .waiting }
        if session.isBusy { return .working }
        return .idle
    }

    /// A context value nobody has refreshed in a while is shown, but marked.
    var contextIsStale: Bool {
        guard let contextMeasuredAt else { return false }
        return Date().timeIntervalSince(contextMeasuredAt) > 120
    }

    /// Last path component of the cwd — the design shows `folder / branch`,
    /// not the full path (which lives in the tooltip).
    var folderName: String {
        (session.cwd as NSString).lastPathComponent
    }

    /// "14m elapsed" while active, "45m ago" once idle — matches the design.
    var elapsedLabel: String? {
        guard let raw = session.elapsedLabel else { return nil }
        return badge == .idle ? "\(raw) ago" : "\(raw) elapsed"
    }

    var tooltip: String {
        var lines = [session.cwd]
        if let firstPrompt, !firstPrompt.isEmpty { lines.append(firstPrompt) }
        if let messageCount { lines.append("\(messageCount) messages") }
        if session.kind == "background" { lines.append("background agent") }
        return lines.joined(separator: "\n")
    }
}
